"""Add plaintext_password to Users

Revision ID: 27bac577588f
Revises: 90b36c2ebd4e
Create Date: 2024-09-02 18:10:53.147157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bac577588f'
down_revision = '90b36c2ebd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaintext_password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plaintext_password')

    # ### end Alembic commands ###
