"""Added Foreign Key

Revision ID: 824e32a377bc
Revises: 01ce1d54d9f0
Create Date: 2024-09-06 21:21:16.152206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824e32a377bc'
down_revision = '01ce1d54d9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=False))
        # Provide a name for the foreign key constraint
        batch_op.create_foreign_key(
            'fk_posts_poster_id',  # Name of the foreign key constraint
            'users',               # Target table
            ['poster_id'],         # Source column(s)
            ['id']                 # Target column(s)
        )
        batch_op.drop_column('author')
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=225), nullable=True))
        batch_op.drop_constraint('fk_posts_poster_id', type_='foreignkey')  # Drop the foreign key constraint by name
        batch_op.drop_column('poster_id')
    # ### end Alembic commands ###

